#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding 14

bspc config split_ratio          0.52
bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#928374'
bspc config borderless_monocle   true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

## Autostart
betterlockscreen -w
#sudo wpa_supplicant -B -D wext -i wlp7s0 -c /etc/wpa_supplicant.conf
#sudo dhcpcd wlp7s0
